Remove osd_subst_env from osd_file and directory interfaces
mamedev/mame pull request #10394
Opened 2022-10-05 01:20 UTC by ajrhacker

This is an alternate means to the same end as PR #9859. The calls to `osd_subst_env` in the various implementations `osd_file::open` and `osd::directory::open` never properly belonged there, and made it impossible to specify certain kinds of filenames (see issue #9822). The major difference between this and #9859 is that environment variable substitution is not performed statically when the values and default values are set, but dynamically when the values are read out if `value_substituted` is called, and the specific getters now do that where appropriate. One technical issue is that, due to dynamic string allocation, the return type of these getters becomes `std::string` rather than `const char *`, but most use cases needed little to no adjustment, with the major exception of `emu_options::state_directory()` due to some dubiously architected pointer storage in the `running_machine` class which I'm somewhat reluctant to touch (because emu.h rebuilds are a pain).

2022-10-05 01:30 UTC, cuavas requested changes
This doesn’t solve the issue properly.  Environment variable substitution should only be applied to path option values that come from INI files or from defaults.  It should *not* be applied to path options that come from the command line, where the shell is responsible performing substitution.  This will do double-substitution on paths supplied on the command line.

2022-10-05 01:38 UTC, ajrhacker commented
I don't think many users intentionally specify environment variables on command lines for MAME, so "double substitution" seems like a red herring. What I think is more likely to happen is the specification of file or directory names that may look like environment variables but shouldn't be substituted even once.

2022-10-05 01:58 UTC, cuavas commented
I’m pretty sure plenty of people use the `~` prefix for home directory substitution in paths on the command line.  Speaking of which, I think this PR will also break that.  If you have a line like this in your INI file on *NIX:
```
rompath /home/shared/mame/roms;~/.mame/roms
```
the `~` is logically at the beginning of a path and should be substituted.  However, with this PR it won’t be substituted because it isn’t at the beginning of the string.  Multi-path options need to be self-aware enough to substitute `~` at the beginning of each path.

2022-10-22 15:18 UTC, ajrhacker commented
I've done a little more work on this, but not enough to resolve one of the major issues. I plan to return to it later.

2022-12-17 12:20 UTC, closed without merging