hng64_3d.ipp : disable use of 32-bit 3D framebuffer for now, it doesn't make too much logical sense
mamedev/mame pull request #10941
Opened 2023-02-27 17:44 UTC by DavidHaywood

2023-02-27 17:47 UTC, DavidHaywood commented
based on the amount of RAM tested for the framebuffer, and the logical issues with how it would interact with the mixer palette controls, it doesn't seem very likely that the framebuffer is storing RGB data.  This does however raise a different question, one of how it stores lighting data, and what we were treating as 'untextured' rgb polygons.

2023-02-28 00:22 UTC, DavidHaywood commented
the colour banding on the original hardware footage
https://i.postimg.cc/PJhkwnRv/sumo2.png
(left in image) also seems to indicate IMHO that it's likely going to be storing the palette index in the framebuffer, and a low precision (4-bit?) lighting value which is to be applied at mix time, not render time.  
were it a full RGB888 framebuffer, I would not expect to see this kind of banding over the texture on original hardware, as it would be able to smoothly interpolate the lighting values.

2023-02-28 16:42 UTC, cuavas requested changes

2023-02-28 16:42 UTC, cuavas commented on src/mame/snk/hng64_3d.ipp
> +	uint16_t unused = chunkOffset_verts[counter++]; (void)unused; // chunkOffset_verts[ xxxx+3 ] is set to 0x70 on some 'blended' objects (fatfurwa translucent globe, buriki shadows, but not on fatfurwa
Please use the `[[maybe_unused]]` attribute to mark intentionally unused variables.

2023-02-28 18:13 UTC, merged