ibm5170.xml: Software list additions
mamedev/mame pull request #11142
Opened 2023-04-22 15:41 UTC by ArcadeShadow

New working software list additions
--------------------------------------------
Basket Playoff (re-release) [Total DOS Collection]
Brutal: Paws of Fury [Total DOS Collection]
Discworld [Total DOS Collection]
Dungeon Master II: The Legend of Skullkeep [Total DOS Collection]
Eye of the Beholder: Trilogy [Total DOS Collection]
Hoyle: Official Book of Games - Volume 3 (VGA, Futura release) [Total DOS Collection]
Risky Woods (Futura release) [Total DOS Collection]
Super Space Invaders (Big Games release) [Total DOS Collection]
The Colonel's Bequest (Futura release) [Total DOS Collection]
Thomas the Tank Engine & Friends - Electronic Paint Box [Total DOS Collection]
Thomas the Tank Engine & Friends - The Collection [Total DOS Collection]

Moved from ibm5150 to ibm5170 software list
--------------------------------------------
Risky Woods (requires hard disk installation)

Removed software list
--------------------------------------------
Eye of the Beholder 3: Assault on Myth Drannor (Eye of Beholder Trilogy release)

2023-04-22 19:22 UTC, DopefishJustin commented
The ibm5150 driver can use hard disks, that isn't grounds for moving an item out of the 5150 softlist.

2023-04-23 08:30 UTC, ArcadeShadow commented
> The ibm5150 driver can use hard disks, that isn't grounds for moving an item out of the 5150 softlist.

The label isn't very clear, but aside from the need to install on a hard disk, it requires a VGA or MCGA card and at least a 286 PC.
![image](https://user-images.githubusercontent.com/26376777/233828735-df7a0e03-85fe-435c-8ef3-66d6010fded3.png)

That's why I moved to the ibm5170 software list

2023-05-23 17:03 UTC, cuavas requested changes

2023-05-25 18:23 UTC, ArcadeShadow commented on hash/ibm5170.xml
> +]]></notes>
fixed

2023-06-22 19:07 UTC, merged