Cdg turbosub - Add new romsets for TurboSub and add start inputs back to new prototype
mamedev/mame pull request #11359
Opened 2023-06-20 21:21 UTC by lupinthird

2023-06-20 21:25 UTC, lupinthird commented
These are the matching TurboSub driver updates for the roms we're sending over to the submission account

2023-06-20 21:34 UTC, simzy39 commented
Are these roms from the collector that owns the turbosub dot com website?

2023-06-20 21:36 UTC, lupinthird commented
Yes, Chris runs the website and he sent them to his cousin (Spindaddy).  These are being released with their knowledge and consent. I worked with Spindaddy to get them working in mame and to update the driver.

2023-06-20 22:16 UTC, philipjbennett requested changes

2023-06-20 22:30 UTC, lupinthird commented on src/mame/misc/esripsys.cpp
> +static INPUT_PORTS_START( turbosubb8 )
This should look much more cleaned up now

2023-06-20 22:30 UTC, lupinthird commented on src/mame/misc/esripsys.cpp
> +	ROM_CONTINUE(                0x20000, 0x2000 )
These are now aligned as they are everywhere else

2023-06-20 22:30 UTC, lupinthird commented on src/mame/misc/esripsys.cpp
>  GAME( 1985, turbosub,  0,        esripsys, turbosub, esripsys_state, init_esripsys, ROT0, "Entertainment Sciences", "Turbo Sub (prototype rev. TSCA)", MACHINE_SUPPORTS_SAVE )
These are all neatly aligned again

2023-06-20 22:53 UTC, philipjbennett approved these changes

2023-06-21 01:15 UTC, merged

2023-06-21 03:26 UTC, simzy39 commented
Can this comment now be removed from the file?
Roms Wanted:  Turbo Sub [later version] (improved gameplay, uses 27512 ROMs)"

2023-06-21 03:33 UTC, lupinthird commented
The turbosub8 set which is the newest release had graphics ROMs that were on 27256s, but the program code was still on 27128s. There may still be a different version of larger combined ROMs in the wild.

2023-06-21 03:35 UTC, lupinthird commented
Most likely turbosub8 was the final release, so maybe? How do we know of the existence of the 27512 ROMs?