megadriv.xml: Added 3 items (2 working), replaced Bad Dump with verified one, fixed titles, added info
mamedev/mame pull request #12171
Opened 2024-03-22 20:56 UTC by ICEknigh7

Not working entry added (for use with the HeartBeat Catalyst fitness sensor):
- Outback Joey (HeartBeat Personal Trainer) [Nikaotix]

Bad Dump replaced with verified one:
- Férias Frustradas do Pica-Pau (Brazil) (fixes GitHub Issue https://github.com/mamedev/mame/issues/11950) [MARCSLASH, arthurthekidboy]

Clones added:
- Sonic The Hedgehog (World, JP2, ripped from Sonic Mega Collection) [Sonic Cult, SonicBlur, Just Me, Haku Ronin]
- Sonic The Hedgehog 2 (prototype 199209xx, pirate) [drx, Hidden Palace]

Fixed descriptions, added info, added entries to lists of missing dumps.

Should contain all the info from the closed PR https://github.com/mamedev/mame/pull/11353 in an easier-to-review form (without grouping the Sega Game Toshokan titles into their own section or doing additional cleanups).

2024-03-22 21:31 UTC, ICEknigh7 commented
For those who don't know what the Heartbeat Catalyst is: https://segaretro.org/HeartBeat_Catalyst
> The HeartBeat Catalyst is a body-mounted [fitness sensor](https://en.wikipedia.org/wiki/Activity_tracker) hardware peripheral which reads players' heart rate, motion, and skin salinity levels for in-game feedback, and is compatible with any [Mega Drive](https://segaretro.org/Mega_Drive) system. Contrary to popular belief, it does not require the [Personal Trainer](https://segaretro.org/Personal_Trainer) to function, with the Catalyst even being sold separately for those who already owned a Mega Drive.[[3]](https://segaretro.org/HeartBeat_Catalyst#cite_note-https:.2F.2Fweb.archive.org.2Fweb.2F20211004063507.2Fhttps:.2F.2Fwww.latimes.com.2Farchives.2Fla-xpm-1994-06-24-ls-7959-story.html-3)[[4]](https://segaretro.org/HeartBeat_Catalyst#cite_note-https:.2F.2Fweb.archive.org.2Fweb.2F20220129122219.2Fhttps:.2F.2Fwww.chicagotribune.com.2Fnews.2Fct-xpm-1994-02-24-9402240306-story.html-4)

2024-03-22 21:45 UTC, angelosa requested changes
I cite myself:
> What he said: either fix the conflicts or start over, 6 months (& 5 reviewers) for a **XML change that should've split in at least 3 different PRs is far from ideal**.
What do you want here: 
1. the Personal Trainer new dump?
2. the Férias Frustradas do Pica-Pau new pirate dump?
3. changes over Sega Game Toshokan?

I don't care it's the same file, **1 and 2 don't fit 3 at all**, essentially not fitting neither **gitflow** (not enough) nor **trunk-based** approaches (too much).

2024-03-22 21:59 UTC, ICEknigh7 commented
Ok, no Sega Game Toshokan fixes, then.

2024-03-25 21:05 UTC, ICEknigh7 commented
I'm also removing the Personal Trainer stuff, should make the PR easier to review.

2024-03-27 21:57 UTC, ICEknigh7 commented
Splitting this one into two.

2024-05-10 04:05 UTC, merged