MultiPCM: fix banking, allow for 512 samples
mamedev/mame pull request #3045
Opened 2018-01-11 20:28 UTC by ValleyBell

The current implementation of the banking system used by Sega Multi 32 and Sega Model 1 machines is pretty hackish and uses the panning setting to decide what bank to use.

After some investigation I came up with a better solution that seems to work as intended:

For Sega Multi 32, the 1 MiB that is bankable is divided into 2 banks of 512 KiB each. OutRunners confirms this - for the first screen it uses samples 0-255, which use the first bank; for the second screen samples 256-512 are used, which use the second bank according to the ROM's sample table.

The Sega Model 1 sound board apparently uses a single 1 MiB bank.

2018-01-11 20:42 UTC, DavidHaywood commented
would this not be better solved by using an address map for the sound chip and allowing the drivers to control the banking scheme? like some other drivers / sound chips do (eg. for the m6295 in many drivers such as kaneko16.cpp) or do you think the actual chips differ?

2018-01-12 00:16 UTC, rb6502 commented
I'm going to second Haze - this can be done entirely externally to the sound chip by having it provide an address map similar to other chips like the OKI6295 and ES5503, and then we've got a much cleaner implementation.

2018-01-12 14:49 UTC, cuavas requested changes
Please use `device_rom_interface` or another mechanism to allow the chips to use an address map.

2018-01-26 18:31 UTC, cuavas commented
Is this still relevant now that #3113 has been merged?

2018-01-31 19:30 UTC, ValleyBell commented
No, that merge request implemented exactly these fixes.

2018-01-31 19:30 UTC, closed without merging