Add luaprinter with centronics and rs232 luaprinter devices
mamedev/mame pull request #7291
Opened 2020-09-26 01:21 UTC by goldnchild

I've tested it with ubuntu, I don't know how it works with mac or windows.

It maintains a luaprinterlist structure and removes the item from the list in the class destructor.

With the luaprinter, you can do things like look at the byte streams:

for example, to inspect the characters in the buffer:
lp1 = manager:machine().lp[1]
a,b,c = lp1:getbuffer()
print(a,b,c)
for i=c,b do print(i+1,a[i+1]) end

It also provides utility functions for printer devices and saving printer bitmaps.

2020-09-26 15:16 UTC, cuavas requested changes
As well as the specific issues commented in-place, the code is borderline unreadable with a mixture of spaces and tabs for indentation, inconsistent indentation and spacing, and no organisation at all in the `luaprinter` class.

Please reformat the code in Allman style with one tab indent per scope level.

Also, organise the `luaprinter` class properly, using the `public`, `protected` and `private` visibility levels appropriately.

I think there are a lot of other design issues with this, but with the code in its current state it’s too much of a mess to understand.

2020-09-26 15:16 UTC, cuavas commented on src/emu/luaprinter.h
> +#include "emu.h"
You shouldn’t include emu.h from headers like this.

2020-09-26 15:16 UTC, cuavas commented on src/emu/luaprinter.h
> +	~luaprinter() { lp_removefromprinterlist(); }
If this is supposed to be a mixin that integrates with the `device_t` lifecycle, it should implement `device_interface`.  Also, passing a string by value like this is usually not what you want to do.

2020-09-26 15:16 UTC, cuavas commented on src/emu/luaprinter.h
> +	static std::vector<luaprinter *> luaprinterlist;
You shouldn’t be doing this.  Use an iterator to walk the device graph and find devices that derive from your mixin.

2020-09-26 15:16 UTC, cuavas commented on src/emu/luaprinter.h
> +		return std::make_tuple(std::ref(m_lp_printerbuffer),m_lp_head,m_lp_tail); };
Exposing implementation details like buffer pointers is generally not a good idea.

2020-09-26 15:16 UTC, cuavas commented on src/emu/luaprinter.h
> +	static time_t m_lp_session_time;
Having a static member for this doesn’t strike me as a good idea.

2020-09-26 20:41 UTC, goldnchild commented
ok, I'll try to figure out how mix in devices work

2020-10-12 18:46 UTC, goldnchild commented
Thanks for looking at it, I'll work on it some more.

2020-10-12 18:46 UTC, closed without merging