segas32.cpp: Add save states, Fix backdrop color fill when screen resolution is changed
mamedev/mame pull request #7583
Opened 2020-12-22 12:32 UTC by cam900

Add notes in segas32.h

2020-12-24 03:42 UTC, cuavas requested changes

2020-12-24 03:42 UTC, cuavas commented on src/mame/includes/segas32.h
> +	std::unique_ptr<int[]> m_bgcolor_line;
You need to use explicit-sized types for things that you’re saving for portability.

2020-12-24 03:42 UTC, cuavas commented on src/mame/video/segas32.cpp
> +		save_item(NAME(m_mixer_control[i]), i);
This shouldn’t need a loop - MAME can save multi-dimensional arrays.

2020-12-26 21:58 UTC, angelosa commented
Again, what is supposed to fix? 
From my mass testing I don't remember such thing as dynamic screen resolution changes that affects back layer. 
Plus iirc only two games even uses the feature, Arabian Fight and Kokoroji 2 ...

2020-12-27 02:11 UTC, cam900 commented
This also fixes darkedge warning screen. (sometimes cropped right)

2020-12-27 03:52 UTC, merged