huc6270.cpp: Implement 4 color background, Add hardware notes
mamedev/mame pull request #7611
Opened 2020-12-30 01:55 UTC by cam900

according from manual.
Fix spacing

2020-12-30 13:36 UTC, angelosa commented on src/devices/video/huc6270.h
> +	// /HSYNC pin related
Function signatures are clear enough to define those as pins, commentary is superfluous.

2020-12-30 14:52 UTC, angelosa commented on src/devices/video/huc6270.h
> +	*/
Internally HuC6270 **is** 16-bit, it's just the interface with PCE HuC6280 that is 8-bit, at least with normal opcodes (no idea with ST0/ST1/ST2 opcodes). And even then, PCFX V810 can do definitely go up to 32, so the whole point is that register access and internal state should be isolated into a single `io_space` that sets up `mem_mask` accordingly and nuke the dual switch-case.

TL;DR both notes are superfluous, plus your commented signatures are wrong (missing mem_mask)

2020-12-30 14:54 UTC, angelosa commented on src/devices/video/huc6270.h
> +
Totally not a fan of having register implementation details in header for visibility reasons, every description should really go near the relevant register fn or at top of .cpp header instead.

2020-12-30 14:55 UTC, angelosa reviewed
Again, where did you test "4 color background"?

2021-01-13 13:45 UTC, angelosa requested changes

2021-01-13 13:45 UTC, angelosa commented on src/devices/video/huc6270.cpp
> +					m_rcr = COMBINE_DATA(&m_rcr) & 0x3ff;
> error: operation on ‘((huc6270_device*)this)->huc6270_device::m_rcr’ may be undefined [-Werror=sequence-point]

2021-01-15 13:38 UTC, cam900 commented
4 color background is confirmed from developer manual but it's seems like rarely used.

2021-01-15 15:08 UTC, angelosa commented
> 4 color background is confirmed from developer manual but it's seems like rarely used.

That means you didn't do your homework. You can either:
1. Find a SW reference that matches your handling;
2. Make a test and run it on HW where it matches your handling. Your [pceas2 source code](https://www.romhacking.net/utilities/839/) can be published at `src/mame/etc/whateverfoo.asm` for now, lacking a better infrastructure for the time being;

Manual documentation note isn't enough proof, also to me it looks like that CG0 or CG1 upper bits can really be 1 rather than 0.
Unlikely but not impossible.

2021-01-15 15:47 UTC, cam900 commented
![0000](https://user-images.githubusercontent.com/19888109/104747207-9960d080-5793-11eb-85b9-a4d97f79f30c.png)
![0001](https://user-images.githubusercontent.com/19888109/104747211-99f96700-5793-11eb-8d22-b94a8a2f059a.png)
![0002](https://user-images.githubusercontent.com/19888109/104747212-9a91fd80-5793-11eb-8a77-92526d8c3849.png)
result of CG0 only, CG1 only, Both; source from https://www.chrismcovell.com/PCEdev/

2021-01-16 15:33 UTC, angelosa commented
Steps to reproduce? Assuming this is [tutorial06_05.pce](https://www.chrismcovell.com/PCEdev/tutorial06.zip) we're talking about I don't see attempts to enable mode 4, or being done so in [06a](https://youtu.be/t4b_kuOL63o) or [06b](https://youtu.be/JYZQcj5zrZE), admittedly I've only seen excerpts to those.

2021-01-16 16:44 UTC, cam900 commented
> Steps to reproduce? Assuming this is [tutorial06_05.pce](https://www.chrismcovell.com/PCEdev/tutorial06.zip) we're talking about I don't see attempts to enable mode 4, or being done so in [06a](https://youtu.be/t4b_kuOL63o) or [06b](https://youtu.be/JYZQcj5zrZE), admittedly I've only seen excerpts to those.

with source code modification, line 77 of INCLUDE/startup.asm controls MWR.

2021-01-22 13:36 UTC, cam900 commented
I close this PR and will reopen when working test code in real hardware is written.

2021-01-22 13:36 UTC, closed without merging