An Unreleased Genius Leader 1500SL?
mamedev/mame pull request #7759
Opened 2021-02-09 17:09 UTC by AlesanddroPB95

This Laptop Is Released In 2003

2021-02-09 18:44 UTC, ajrhacker requested changes
Commits that add new machines should follow the standard format, beginning with the line "New machines marked as NOT_WORKING" (in this case).

2021-02-09 18:44 UTC, ajrhacker commented on src/mame/drivers/prestige.cpp
> +
This isn't declared, which will cause compilation errors. Since it also isn't used, it would probably best be removed.

2021-02-09 19:31 UTC, Tafoid commented on src/mame/drivers/prestige.cpp
> +ROM_END
I'm confused, too,  Your added bios rom for gl1500sl is 100% the same as the current gl6000sl in source.
Can you explain how or what brings you to this conclusion that these are the same?

2021-02-10 14:19 UTC, cuavas commented
I don’t see the point of this.  It doesn’t seem to add anything useful

2021-02-13 12:54 UTC, closed without merging