Build fix on mac: 10 ^ 7 hits the -Wxor-used-as-pow check
mamedev/mame pull request #8828
Opened 2021-11-14 11:32 UTC by yukaritamura

On building with recent clang on mac, 10 ^ N hits -Wxor-used-as-pow
check. This happens only when a left value is 10, and we can explicitly
say xor to express an exclusive OR operation.

This simple patch replace existing '^'s with 'xor's so that we can
compile it on recent mac, and the code looks consistent in the file.

2021-11-14 13:29 UTC, cuavas requested changes
This warning is supposed to be disabled for sufficiently new clang versions.  See here: https://github.com/mamedev/mame/blob/mame0237/scripts/genie.lua#L1102

The trouble is, Apple uses stupid “vanity versions” for clang that are different to what everyone else uses.  You need to improve detection of sufficiently new clang versions there, not change this source file.

2021-11-14 16:34 UTC, rb6502 commented
What Clang/Xcode version and arch is this?  I just built cmi.cpp fine on Xcode 13 on Intel.

2021-11-18 00:02 UTC, rb6502 commented
I've now built with Xcode 13 on both Intel and AArch64/M1 and not had any problems.  @yukaritamura can you give more details on your build environment?

2021-11-29 16:54 UTC, rb6502 commented
I'm closing this because I can't reproduce it on either Intel or M1 and the submitter hasn't replied to our questions.

2021-11-29 16:54 UTC, closed without merging