Add driver for RC2014 Mini
mamedev/mame pull request #9331
Opened 2022-02-23 09:20 UTC by cpswan

Driver for [RC2014 Mini](https://rc2014.co.uk/full-kits/rc2014-mini/) based on [gsz80.cpp](https://github.com/mamedev/mame/blob/master/src/mame/drivers/gsz80.cpp) from #6643

2022-02-23 09:45 UTC, Robbbert commented
mame.lst - carriage return at end of file is missing.

mess.flt, mess.lua changes haven't been included in the PR

2022-02-23 09:53 UTC, startaq commented
If this is just a copy of gsz80.cpp then you can just add a new rom section to  it.

2022-02-23 10:10 UTC, cpswan commented
@Robbbert [b1c9aae](https://github.com/mamedev/mame/pull/9331/commits/b1c9aae015d52c6047496168e569a2156371165e) should fix the points that you raise.

@startaq the ROM for RC2014 56k BASIC is the same one as used by gsz80.cpp, as the RC2014 modular design is just Grant Searle's system split into modules; then the Mini brings together the core modules onto a single board.

2022-02-23 14:09 UTC, cpswan commented
@startaq I've switched the ROM to the RC2014 specific Small Computer Monitor (SCM), and in doing that realised that I shouldn't have been using 56k BASIC at all, as the RC2014 Mini has 32K RAM, so I've fixed that in the memory map.

I can add the 32K BASIC ROM if you can point me at a good simple example of where multiple ROMs are defined for a driver?

2022-02-23 14:17 UTC, startaq commented
Well my point was that the drivers seem largely identical, so it might make sense to put both into the same file.

2022-02-23 16:45 UTC, cpswan commented
@startaq it's all in gsz80.cpp now.

2022-02-24 16:01 UTC, cuavas requested changes

2022-02-24 17:31 UTC, cpswan commented on src/mame/drivers/gsz80.cpp
> +}
removed

2022-02-24 17:31 UTC, cpswan commented on src/mame/drivers/gsz80.cpp
> +		, m_acia(*this, "acia")         // Tag name for UART is "acia"
done, and class simplified

2022-02-24 17:32 UTC, cpswan commented on src/mame/drivers/gsz80.cpp
> +}
done

2022-02-24 17:49 UTC, happppp commented
The hardware specs you're emulating match this: http://searle.x10host.com/z80/SimpleZ80_32K.html
"rc2014mini_32k.bin" is the same as ROM_32K.HEX from there.

RF2014 Mini has a 512x8 ROM instead, with 3 jumpers for bankswitching, see schematics: https://rc2014.co.uk/full-kits/rc2014-mini/

2022-02-24 18:13 UTC, cpswan commented
@happppp I'm not surprised that @RFC2795 got the 32K BASIC 'R' ROM from Grant Searle, given that the 56K BASIC 'K' ROM is from Grant. As I said in an earlier comment:
> the RC2014 modular design is just Grant Searle's system split into modules; then the Mini brings together the core modules onto a single board

As the jumpers on the RC2014 Mini are for selecting 8K pages from a 64K ROM it seemed like the more MAMEish way to do things would be to present those 8K pages as selectable BIOSes (in this case selected in MAME rather than by setting jumpers). Though I can see a counter argument that jumpers would be more authentic to the original hardware.

6 of the 8 pages in the factory ROM (labelled R0000009) are empty, which offers the possibility of using the space for different firmware, but there's nothing interesting there out of the box for the various intermediate jumper settings.

2022-02-24 20:22 UTC, cpswan commented
@happppp thinking about it some more, I guess the MAME way is to be as authentic as possible to the original hardware (and the way that ROMs are presented). Can you please point me at a driver or two that uses jumpers for bank selection from a ROM, and I'll have a go at implementing the A13/14/15 jumpers on the Mini?

2022-02-24 20:42 UTC, happppp commented
Off the top of my head, no I don't know a driver that bankswitches the program rom with jumpers.
You can do it with these: PORT_CONFNAME/PORT_CONFSETTING, INPUT_CHANGED_MEMBER, required_memory_bank

2022-02-26 16:36 UTC, cpswan commented
@happppp Latest push uses jumpers to select between BASIC and SCM, and is making use of the full r0000009.bin ROM.

2022-02-26 21:24 UTC, cpswan commented
@happppp the last few commits should take care of your earlier comments. Thanks for being so patient as I blunder around with this. "We do these things not because they are easy, but because we thought they would be easy...". I've learned a lot more than I expected to on this journey so far, but I'm still not a minimally competent C++ programmer, and I'm still borrowing too heavily from old drivers (and snippets from forks people have pointed me at) that aren't up to scratch with current conventions.

2022-02-26 21:25 UTC, cpswan commented on src/mame/drivers/gsz80.cpp
> +	PORT_DIPSETTING( 0x7, "SCM" )
done in [aa0a830](https://github.com/mamedev/mame/pull/9331/commits/aa0a830d771db9fe890b330cc44d664de096ab00)

2022-02-26 22:29 UTC, happppp commented
optional_ioport can be changed to required
m_region_maincpu can be removed as it's unused.
void update_banks(); as well

Is "ROM" a good name for that CONFNAME? If you want it to be brief, "ROM Bank" describes it better.
Is that github link to that rom folder ok to put in our source? I thought these files were free to use but now I see Microsoft Basic in there and I'm not sure anymore.

2022-02-26 22:55 UTC, cpswan commented
@happppp most recent comments dealt with

2022-02-27 06:02 UTC, cuavas requested changes
I think that’s the last issue if @happppp doesn’t notice anything else.

2022-02-27 06:02 UTC, cuavas commented on src/mame/drivers/gsz80.cpp
> +	map(0x0000, 0x1fff).rom().bankr("bank");
You shouldn’t have the `.rom()` in there – the `.bankr("bank")` is overriding it.  It’s confusing like this.  It should just have the `.bankr("bank")`

2022-02-28 10:08 UTC, merged