igs017.cpp, igs022.cpp: Improved protection and decryption. Moved protection data to external files
mamedev/mame pull request #9890
Opened 2022-06-05 14:52 UTC by LucaElia

igs017.cpp: Improved protection and decryption [Luca Elia]
- Implemented "magic" i/o as a memory map (IGS_MUX) for added flexibility
- Hooked up IGS_INCDEC protection to cpoker2, tarzanc, spkrform, starzan
- Implemented specific IGS_INC protection in cpoker2
- Hooked up improved IGS022 protection to lhzb2, sqlz2
- Added IGS025 string protection to lhzb2, lhzb2a, mgcs, spkrform, slqz2, starzan, tarzanc, tjsb
- Palette scramble and tweaked tiles decryption in tarzanc (used also by starzan, happyskl, cpoker2)
- Decrypted sprites in tarzanc and starzan (used also by happyskl)
- Lamps and layout for starzan, happyskl, cpoker2
- Cleaned up/finished hopper emulation, added diplocations
- Joystick inputs in mgcs
- Finished inputs in spkrform. Allow hiding gambling (switching to Formosa and back)
- Moved protection data to external files

igs022.cpp: Fixes for igs017.cpp games [Luca Elia, RockyWall]
- Fixed initial auto-DMA mode
- Enlarged internal RAM. Added stack
- Fixed command 12: Copy -> Stack Push
- Added command 45: Stack Pop
- Fixed command 6d opcode 1: Add Imm -> Sub Values
- Added command 6d opcode 0: Add Values
- Extended logging

Machines promoted to working
----------------------------
Tarzan Chuang Tian Guan (China, V109C, set 1) [Luca Elia, iq_132, Ivan Vangelista, Guru, Dyq, bnathan]
Super Tarzan (Italy, V100I) [Luca Elia, iq_132, Ivan Vangelista, f205v, Mirko Buffoni]
Happy Skill (Italy, V611IT) [Luca Elia, Ivan Vangelista, Caius, The Dumping Union]
Champion Poker 2 (V100A) [Luca Elia, Ivan Vangelista, Jorge Silva, Fernando Oliveira]
Long Hu Zhengba 2 (China, set 1) [Luca Elia, RockyWall, David Haywood, iq_132, Pierpaolo Prazzoli, XingXing]
Shuang Long Qiang Zhu 2 VS (China, VS203J) [Luca Elia, RockyWall, David Haywood, iq_132, Pierpaolo Prazzoli, XingXing]

Clones promoted to working
--------------------------
Super Poker (V100xD03) / Formosa [Luca Elia, ANY]

2022-06-05 17:00 UTC, cuavas requested changes
This looks a lot better than last time.

There are a few `logerror` that are probably going to be a bit spammy and have a performance impact – think about which ones can be replaced with `LOG` from logmacro.h so they can be enabled conditionally.  It’s fine to leave in `logerror` for the ones for things that are not understood, but the ones for debugging the properly emulated functions probably don’t need to be active by default.

The other comments should all be pretty simple to address.  Thanks for sorting out the major issues.

2022-06-11 15:10 UTC, LucaElia commented on src/mame/drivers/igs017.cpp
> +	, m_region_key(*this, "key")
Changed to DEVICE_SELF

2022-06-11 15:11 UTC, LucaElia commented on src/mame/drivers/igs017.cpp
> +	logerror("%s: exec bitswap on port %02x = %02x - bit0 %x, xor0 %x, word %04x -> %04x\n", machine().describe_context(), offset, data, bit0, xor0, x, m_word);
Converted to logmacro.

2022-06-11 15:11 UTC, LucaElia commented on src/mame/drivers/igs017.cpp
> +	return;
Yes, it slipped through. Removed.

2022-06-11 15:12 UTC, LucaElia commented on src/mame/drivers/igs017.cpp
> +	return 0x00;
Changed to return space.unmap().

2022-06-11 15:16 UTC, LucaElia commented on src/mame/drivers/igs017.cpp
> +	u8 res = bitswap<16>(m_val, 0,0,0,0,0,0,0,0, 5,2,9,7,10,13,12,15) & 0xff;
Changed to bitswap<8>. I'm too used to the old BITSWAP16 macro I guess.

2022-06-11 15:16 UTC, LucaElia commented on src/mame/drivers/igs017.cpp
> +	PORT_BIT( 0x40, IP_ACTIVE_LOW, IPT_BUTTON5        ) PORT_NAME("Hold 5 / Tile in Double Up?") // (2P B in test mode)
Done.

2022-06-11 15:17 UTC, LucaElia commented on src/mame/drivers/igs017.cpp
> +	PORT_BIT( 0x20, IP_ACTIVE_LOW, IPT_BUTTON5        ) PORT_PLAYER(2)   // unused?      (2P E in test mode)
Done.

2022-06-11 15:19 UTC, LucaElia commented on src/mame/drivers/igs017.cpp
> +	PORT_BIT( 0x02, IP_ACTIVE_LOW,  IPT_SERVICE3  ) PORT_NAME("Clear") // shown in test mode
There are actually the "Hide Gambling" feature. I've improved on it a bit and standardized to IPT_SERVICE1 to activate it, while also moving "Statistics" to IPT_GAMBLE_BOOK across games.

2022-06-11 15:20 UTC, LucaElia commented on src/mame/machine/igs022.cpp
> +	std::stringstream stream;
Correct. Changed to std::ostringstream.

2022-06-11 15:21 UTC, LucaElia commented on src/mame/machine/igs022.cpp
> +	return stream.str();
Changed as suggested.

2022-06-11 17:08 UTC, merged